### ISSUE TITLE
Jazzy: Documentation

### ISSUE THREAD

**Issue by mikeferguson** [ros-perception/image_pipeline#848]
Currently, the documentation still points at the wiki, which is deprecated and falling apart:

 - [x] Figure out exactly where/how we should host docs
 - [x] Update docs for nodelet->component updates

Packages to port:

 - [x] camera_calibration
 - [x] depth_image_proc
 - [x] image_pipeline
 - [x] image_proc
 - [x] image_publisher
 - [x] image_rotate
 - [x] image_view
 - [x] stereo_image_proc

Particular things that need to be added to documentation:

 - [x] Proper syntax for image_transport (https://github.com/ros-perception/image_pipeline/issues/824)
 - [x] How to use components (https://github.com/ros-perception/image_pipeline/issues/823)
 - [x] How to use standalone nodes (and why you should prefer components - with link to the component white paper)
 - [x] Add the exact formats supported by convert_metric and register nodes (https://github.com/ros-perception/image_pipeline/issues/794)
 - [x] Notes about how to remap topics - for instance, you have to remap "image/image_raw" if that is the subscribed topic, you can't just remap "image". Especially noteworthy for stereo_image_proc (see notes in https://github.com/ros-perception/image_pipeline/pull/903)
 - [x] Document the radial nodes (they aren't in the ROS Wiki at all). Were originally added in https://github.com/ros-perception/image_pipeline/pull/122
 - [x] Make sure we include the camera info stuff: http://wiki.ros.org/image_pipeline/CameraInfo
 - [ ] Port http://wiki.ros.org/stereo_image_proc/Tutorials/Using%20OpenCV%20for%20Image%20Processing - but it should probably go under image_pipeline specifically (and be linked from other places)

Document changes in Jazzy:

- [x] all nodes with image_transport now properly support remapping, if you were manually remapping topics your remapping rules might need to be updated
- [x] extract_images and stereo_view - parameter "transport" is renamed to the more consistent "image_transport"
- [x] point_cloud nodes now support image_transport - but note that depth topics use parameter "depth_image_transport"
- [x] renamed input topics of xyz_radial: "image_raw" -> "depth/image_raw" (#906)
- [x] renamed input topics of xyzrgb_radial: "depth_registered/image_rect" -> "depth/image_raw" and "rgb/image_rect_color" -> "rgb/image_raw" (#906)

**Comment by mikeferguson** [comment]
* image_proc docs: https://github.com/ros-perception/image_pipeline/pull/925
 * depth_image_proc docs: https://github.com/ros-perception/image_pipeline/pull/926

**Comment by mikeferguson** [comment]
https://github.com/ros-perception/image_pipeline/pull/928 ports stereo_image_proc

**Comment by mikeferguson** [comment]
#929 ports image_pipeline overview and the CameraInfo page

**Comment by mikeferguson** [comment]
https://github.com/ros-perception/image_pipeline/pull/936 adds image_rotate and image_publisher - only camera_calibration remains

**Comment by mikeferguson** [comment]
#937 is the start of camera_calibration

**Comment by mikeferguson** [comment]
PRs are merged or open for all packages
